---

- name: Task 1
  debug:
    msg: "Task one"

- name: Task 2
  debug:
    msg: "Task two"

- name: Exec single shell command
  shell: echo "1"
  
- name: Exec multi commands using &&
  shell: echo "1" && echo "2"
